import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/components/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex px-5 w-full min-h-lm items-center justify-center bg-gradient-to-b from-gray-50 via-gray-50 to-gray-100 py-20">
        <div className="container">
          <div className="md:w-7/12">
            <h1 className="  text-black-2 text-center md:text-left text-3xl font-bold leading-tight tracking-tight sm:text-5xl">
            Tecnología Para Todos
              
            </h1>
            <p className="pt-5 text-center md:text-left leading-tight tracking-tight text-base sm:text-lg font-medium">
            En LM Tech nos centramos en tu negocio y en tus necesidades de tecnología y software. Nos preocupamos en ser parte de una sociedad que avanza hacia el futuro y nos encargamos de que progreses en ello.
            </p>
          </div>
        </div>
      </section>
      <section className="flex flex-1 justify-center bg-gradient-to-b from-gray-50 via-gray-50 to-gray-100 py-20">
        <h1>Nosotros</h1>
        <h1 className="px-5 text-center text-4xl font-bold leading-tight tracking-tight sm:mt-4 sm:text-6xl">
          Next.js
          <br />
          Advanced Starter 1
        </h1>
      </section>
    </>
  );
}
