import Head from "next/head";
import Image from "next/image";
import earth1 from '../../public/earth8.jpg'
// import styles from "@/components/styles/Home.module.css";
import bg from "../../public/portada.webp";
import bg2 from "../../public/overlay-pattern-black.png";
import Link from "next/link";
import { ServiceItem } from "../components/ServiceItem";
import { BsHddNetwork} from "react-icons/bs";
import { VscCode} from "react-icons/vsc";
import { BiDevices} from "react-icons/bi";
import { Carousel } from "../components/Carousel";
import { Carousel2 } from "../components/carousel2";


export default function Home() {
  // const styles = {
  //   bgFront: {
  //     backgroundImage: `url(${bg2.src}),url(${bg.src})`,
  //     backgroundPosition: '77% center',
  //   backgroundSize: 'auto , cover',

  //     // ':hover': {
  //     //   border: '1px solid black'
  //     // },

  //     '@media (min-width: 768px)': {
  //       width: '100%',

  //       ':hover': {
  //         background: 'white',
  //       }
  //     }
  //   },
  //   primary: {
  //     background: 'green'
  //   },
  //   warning: {
  //     background: 'yellow'
  //   },
  // }
  return (
    <>
      <Head>
        <title>LM Tech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx>{`
        .bg-front {
          background-image: none;
          background-position: 77% center;
          background-size: cover;
        }
        .logo {
          width: 80%;
          margin: auto;
        }
        @media (min-width: 768px) {
          .bg-front {
            background-image: url(${bg.src});
            background-position: 50% center;
            background-size: cover;
          }
        }
        @media (min-width: 960px) {
          .bg-front {
            background-image: url(${bg.src});
            background-position: 30% center;
            background-size: cover;
          }
          
        }
        // @media (max-width: 768px) {
        //   .bg-front::before {
        //     content: "";
        //     top: 0;
        //     left: 0;
        //     bottom: 0;
        //     right: 0;
        //     position: absolute;

        //     background-color: hsl(0deg 0% 100% / 68%);
        //     background-position: 77% center;
        //     background-size: auto, cover;
        //   }
        // }
      `}</style>
      <section  className="bg-front grid w-full items-center ">
        <div className="col-start-1 row-start-1 min-h-lm hidden md:block"></div>
        <div className="col-start-1 row-start-1 flex flex-1 w-full h-full flex-col">
          <div className="py-10 px-5 flex flex-1 w-full items-center  ">
            <div className="w-full md:w-10/12 m-auto">
              <div className="md:w-8/12  md:text-black-2 text-center md:text-left">
                {/* <Image priority src="/logo.svg" fill alt="LM Tech" /> */}
                <img className="w-3/5 m-0 hidden md:block" src="/logo.svg" alt="" />

                <h1 className=" mt-7 montserrat text-6xl font-bold leading-[-1rem] md:leading-tight tracking-tight sm:text-6xl">
                  Tecnología Para <br className="block md:hidden"></br> Todos
                </h1>
                <p className="pt-7 montserrat text-center md:text-left leading-tight  text-xl sm:text-lg font-semibold md:pr-0 lg:pr-24">
                  En LM Tech nos centramos en tu negocio y en tus necesidades de tecnología y software. Nos preocupamos
                  en ser parte de una sociedad que avanza hacia el futuro y nos encargamos de que progreses en ello.
                </p>
                <div className="flex-col md:flex-row m-auto md:mx-0 p-2 md:p-0 w-full flex gap-4 max-w-[400px] my-8 md:mb-0">
                  <Link
                    href={"/contacto"}
                    className="font-normal text-xl rounded-md text-center px-4 py-2 w-full bg-primary text-white"
                  >
                    Cotizar
                  </Link>
                  <Link
                    href={"/contacto"}
                    className="font-bold text-xl rounded-md text-center px-4 py-2 w-full text-primary border border-primary "
                  >
                    Productos
                  </Link>
                </div>
              </div>
            </div>
          </div>
          <div className="">
            <img className="purple-bottom" src="/purple-bottom.svg" alt="" />
          </div>
        </div>
      </section>

      <section className="flex flex-col flex-1 justify-center bg-black-1 py-20 text-white text-center">
        <div className="py-10 px-5 flex flex-1 w-full items-center flex-col ">
          <div className="w-full md:w-11/12 m-auto">
            <h1 className="px-5 text-4xl font-semibold md:font-bold leading-tight  mb-4 sm:text-5xl">
              Habilidades para mejorar tu Negocio
            </h1>
              <p className=" md:p-7 md:w-11/12 lg:w-10/12 m-auto  text-xl sm:text-xl font-normal text-stone-400">
              Contamos con servicios desde la creacion e implementacion de redes y hardware, creacion de plataformas y sistemas de informacion, e integracion de nuevos desarrollos.
              </p>
          </div>
          <div className="w-full md:w-12/12 flex flex-row pt-5 md:pt-5 ">
            <div className="md:w-5/12 hidden md:flex h-full relative">
              {/* <img src="/earth8.jpg" className="max-w-[500px] w-full pt-4 " alt="" /> */}
              <Image priority src={earth1 } object-fit="fill" alt="LM Tech" /> 
            </div>

         
          <div className="w-full md:w-6/12 flex py-20 flex-col md:flex-col gap-28 md:gap-20 place-items-end">
            <ServiceItem img="/redes.svg" title="Redes y Hardware" description="
            El flujo de datos e informacion en los negocios es fundamental. Creamos las redes que den soporte a tus necesidades de conectividad, tanto dentro de tu negocio como hacia internet. Llevamos tu negocio a la nube.
            ">
              <BsHddNetwork/>
            </ServiceItem>
            <ServiceItem img="/plataformas.svg" title="Plataformas digitales" description="
            Creamos plataformas que se integren a tus actuales sistemas, o creamos nuevas plataformas basadas en las nuevas formas de relacionarnos. Nuestra plataforma de módulos permite el control de tu negocio y la visualización en tiempo real de tu información.
            ">
              <BiDevices/>
            </ServiceItem>
            <ServiceItem title="Desarrollo de Software" description="
            Somos desarrolladores, por lo que entregamos soluciones a las problematicas que tengas mediante el desarrollo de software. Las aplicaciones web en la nube, las APIs de integracion de datos y el desarrollo Mobile son el proximo paso de tu negocio.
            ">
              <VscCode/>
            </ServiceItem>
          </div>
          <div className="md:w-1/12 hidden md:flex h-full"></div>
          </div>
        </div>
      </section>



      <section className="flex flex-col flex-1 justify-center bg-gradient-to-b from-[#B9C7CF] to-[#E5E6F9] py-20 text-black text-center">
        <div className="py-10 px-5 flex flex-1 w-full items-center flex-col ">
          <div className="w-full md:w-11/12 m-auto">
            <h1 className="px-5 text-4xl font-semibold md:font-bold leading-tight  mb-4 sm:text-5xl">
              Nuestro Proceso de Creación
            </h1>
              <p className=" pb-7 md:p-7 md:w-11/12 lg:w-10/12 m-auto  text-xl sm:text-xl font-normal ">
              Hablemos de tus necesidades, busquemos oportunidades y hagamos crecer tu negocio con tecnología.

              </p>
          </div>
          
        </div>
        <Carousel/>
      </section>
    </>
  );
}
